import type { Artwork } from "@/types/artwork"

export const artworks: Artwork[] = [
  {
    id: 1,
    title: "Sinaloa - Morcon",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/Sinaloa 20x lana boliviana MORCON Texana.png",
  },
  {
    id: 2,
    title: "Sinaloa - Morcon Gris Cristal",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/Sinaloa 20x MORCON gris cristal Texana.png",
  },
  {
    id: 3,
    title: "Sinaloa - Morcon",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/Sinaloa 20x MORCON Texana.png",
  },
  {
    id: 4,
    title: "Roper - Tombstone Negro",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/ROPER 20x TOMBSTONE Texana.png",
  },
  {
    id: 5,
    title: "Roper - Tombstone Arena",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/ROPER 20x TOMBSTONE.  Arena Texana.png",
  },
  {
    id: 6,
    title: "Roper - Tombstone Nutria",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/ROPER Nutria 20x TOMBSTONE Texana.png",
  },
  {
    id: 7,
    title: "Este Oeste - Morcon 20X",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/Este oeste 20x lana boliviana MORCON Texana.png",
  },
  {
    id: 8,
    title: "Este Oeste - Morcon Naranja",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/Este oeste MORCON 20x naranja Texana.png",
  },
  {
    id: 9,
    title: "Brasil Roja - Morcon 20X",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/Brasil roja 20x MORCON Texana.png",
  },
  {
    id: 18,
    title: "Este Oeste - Tombstone 20X",
    artist: "20X Lana Boliviana",
    year: 2026,
    image: "/Este oeste 20x TOMBSTONE Texana.png",
  },
  {
    id: 15,
    title: "Luis R Conríquez - Laredo Texana 4X",
    artist: "Colaboraciones Artistas",
    year: 2026,
    image: "/Luis R Conriquez 4x Laredo Texana.png",
  },
  {
    id: 16,
    title: "Carin Leon - Laredo Texana 4X",
    artist: "Colaboraciones Artistas",
    year: 2026,
    image: "/Carin Leon 4x Laredo Texana.png",
  },
  {
    id: 19,
    title: "El KOMANDER - Tombstone Sombrero",
    artist: "Colaboraciones Artistas",
    year: 2026,
    image: "/El KOMANDER TOMBSTONE Sombrero.png",
  },
  {
    id: 10,
    title: "Este Oeste - Tombstone 5000X",
    artist: "Tombstone",
    year: 2026,
    image: "/Este oeste 5000x TOMBSTONE Sombrero.png",
  },
  {
    id: 11,
    title: "Este Oeste - Gris Granito",
    artist: "Tombstone",
    year: 2026,
    image: "/Este Oeste- Gris Granito.png",
  },
  {
    id: 12,
    title: "Los Alegres del Barranco - Tombstone 5000X",
    artist: "Tombstone",
    year: 2026,
    image: "/Los alegres del barranco 5000x TOMBSTONE Sombrero.png",
  },
  {
    id: 13,
    title: "Sombrero Tombstone 10,000X",
    artist: "Tombstone",
    year: 2026,
    image: "/TOMBSTONE 10,000x.png",
  },
  {
    id: 17,
    title: "Toquillas Hilo de Plata",
    artist: "Accesorios",
    year: 2026,
    image: "/TOQUILLAS HILO DE PLATA.png",
  },
  {
    id: 14,
    title: "Espuma Limpieza para Texana",
    artist: "Accesorios",
    year: 2026,
    image: "/Espuma limpieza para TEXANA.png",
  },
]
